export const profiles = [
  {
    id: "1",
    rating: 5,
    name: "Pele White's Expertise",
    preferredLocations: ["New York", "USA"],
    phoneNumber: "+12348191911",
    location: "Calgary",
    yearStarted: "2009",
    flightsMade: 2317,
    workPlace: "EXPERUM ENTIA",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "Instagram",
        link: "https://www.instagram.com/pele_white_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Facebook",
        link: "https://www.facebook.com/pelewhiteexpertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Twitter",
        link: "https://www.twitter.com/pelewhiteexpertise/",
      },
    ],
    description:
      "Cliquae experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
    imgSrc: "/assets/images/smiling-beauty.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "John Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 5,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 5,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "4 days ago",
      },
    ],
  },
  {
    id: "2",
    rating: 4,
    name: "Jon Fonseca's Expertise",
    preferredLocations: ["California", "USA"],
    phoneNumber: "+12348191911",
    location: "Ontario",
    yearStarted: "2010",
    flightsMade: 2864,
    workPlace: "EXPERUM ENTIA",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "Instagram",
        link: "https://www.instagram.com/pele_white_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Facebook",
        link: "https://www.facebook.com/pelewhiteexpertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Twitter",
        link: "https://www.twitter.com/pelewhiteexpertise/",
      },
    ],
    description:
      "Cliquae experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
    imgSrc: "/assets/images/smiling-handsome.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "John Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 5,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 5,
        time: "4 days ago",
      },
    ],
  },
  {
    id: "3",
    rating: 3,
    name: "Mulbery Smith's Expertise",
    preferredLocations: ["FLorida", "USA"],
    phoneNumber: "+12348191911",
    location: "Sascatchewan",
    yearStarted: "2015",
    flightsMade: 3627,
    workPlace: "EXPERUM ENTIA",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "Instagram",
        link: "https://www.instagram.com/pele_white_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Facebook",
        link: "https://www.facebook.com/pelewhiteexpertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Twitter",
        link: "https://www.twitter.com/pelewhiteexpertise/",
      },
    ],
    description:
      "Cliquae experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
    imgSrc: "/assets/images/smiling-calling.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "John Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 3,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 5,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "4 days ago",
      },
    ],
  },
  {
    id: "4",
    rating: 5,
    name: "Pele White's Expertise",
    preferredLocations: ["New Jersey", "New York", "USA"],
    phoneNumber: "+12348181811",
    location: "Newfoundland",
    yearStarted: "2009",
    flightsMade: 756,
    workPlace: "EXPERUM ENTIA",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "Instagram",
        link: "https://www.instagram.com/pele_white_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Facebook",
        link: "https://www.facebook.com/pelewhiteexpertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Twitter",
        link: "https://www.twitter.com/pelewhiteexpertise/",
      },
    ],
    description:
      "Cliquae experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
    imgSrc: "/assets/images/smiling-beauty.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "John Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 5,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 5,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "4 days ago",
      },
    ],
  },
  {
    id: "5",
    rating: 4,
    name: "Jon Fonseca's Expertise",
    preferredLocations: ["New York", "USA"],
    phoneNumber: "+12348191911",
    flightsMade: 1364,
    location: "Calgary",
    yearStarted: "2009",
    workPlace: "EXPERUM ENTIA",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "Instagram",
        link: "https://www.instagram.com/pele_white_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Facebook",
        link: "https://www.facebook.com/pelewhiteexpertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Twitter",
        link: "https://www.twitter.com/pelewhiteexpertise/",
      },
    ],
    description:
      "Cliquae experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
    imgSrc: "/assets/images/smiling-handsome.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "John Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 3,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 5,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "4 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 5,
        time: "4 days ago",
      },
    ],
  },
  {
    id: crypto.randomUUID(),
    rating: 3,
    name: "Mulbery Smith's Expertise",
    preferredLocations: ["New York", "USA"],
    phoneNumber: "+12348191911",
    location: "Calgary",
    flightsMade: 2864,
    yearStarted: "2009",
    workPlace: "EXPERUM ENTIA",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "Instagram",
        link: "https://www.instagram.com/pele_white_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Facebook",
        link: "https://www.facebook.com/pelewhiteexpertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Twitter",
        link: "https://www.twitter.com/pelewhiteexpertise/",
      },
    ],
    description:
      "Cliquae experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
    imgSrc: "/assets/images/smiling-calling.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "John Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 2,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 5,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "Experum entia nos ut occabor eressim que volut as eum, nos mi, quiae sitaero mo eaque nis maio molo corepero evendanime cusant dusandes moluptatet",
        rating: 4,
        time: "4 days ago",
      },
    ],
  },
];
