export const profiles = [
  {
    id: "1",
    slug: "pele.white",
    rating: 5,
    name: "Pele White's Expertise",
    preferredLocations: ["New York", "USA"],
    phoneNumber: "+12348191911",
    location: "Calgary",
    yearStarted: "2009",
    flightsMade: 2317,
    workPlace: "EXPERUM ENTIA",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "Instagram",
        link: "https://www.instagram.com/pele_white_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Facebook",
        link: "https://www.facebook.com/pelewhiteexpertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Twitter",
        link: "https://www.twitter.com/pelewhiteexpertise/",
      },
    ],
    description:
      "With over a decade in the aviation consulting industry, Pele White brings a wealth of expertise in logistical planning, flight coordination, and client relations. Based in Calgary, Pele has established a reputation for delivering seamless travel solutions to clients across the United States and beyond.",
    imgSrc: "/assets/images/smiling-beauty.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "John Doe",
        text: "Pele provided outstanding support during a complex travel arrangement. His attention to detail and dedication to client satisfaction was unmatched.",
        rating: 5,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jane Doe",
        text: "The service was exceptional, from planning to execution. Pele went above and beyond to ensure everything went smoothly.",
        rating: 4,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Alice Kim",
        text: "Highly recommend Pele's expertise! He made our corporate travel plans seamless and stress-free.",
        rating: 5,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Mike Johnson",
        text: "A fantastic experience working with Pele. Every detail was meticulously handled!",
        rating: 4,
        time: "4 days ago",
      },
    ],
  },
  {
    id: "2",
    rating: 4,
    slug: "jon.fonseca",
    name: "Jon Fonseca's Expertise",
    preferredLocations: ["California", "USA"],
    phoneNumber: "+12348191911",
    location: "Ontario",
    yearStarted: "2010",
    flightsMade: 2864,
    workPlace: "EXPERUM ENTIA",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "Instagram",
        link: "https://www.instagram.com/jon_fonseca_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Facebook",
        link: "https://www.facebook.com/jonfonsecaexpertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Twitter",
        link: "https://www.twitter.com/jonfonsecaexpertise/",
      },
    ],
    description:
      "Jon Fonseca is a seasoned travel and logistics coordinator, specializing in arranging travel for high-profile clients and organizations across California. Known for his strategic approach and excellent client rapport, Jon has successfully managed over 2,800 flights, ensuring efficient and comfortable journeys.",
    imgSrc: "/assets/images/smiling-handsome.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "Sarah Lee",
        text: "Jon's expertise in planning was exactly what we needed for our busy schedule. He handled everything seamlessly!",
        rating: 4,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "David Kim",
        text: "Great service from Jon. He was very attentive and made sure our needs were met throughout the entire process.",
        rating: 5,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Emily Tran",
        text: "Jon went above and beyond to accommodate our travel requests, even with last-minute changes.",
        rating: 4,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Michael Chen",
        text: "Professional, efficient, and a pleasure to work with. I highly recommend Jon's services.",
        rating: 5,
        time: "4 days ago",
      },
    ],
  },
  {
    id: "3",
    rating: 3,
    slug: "mulbery.smith",
    name: "Mulbery Smith's Expertise",
    preferredLocations: ["Florida", "USA"],
    phoneNumber: "+12348191911",
    location: "Saskatchewan",
    yearStarted: "2015",
    flightsMade: 3627,
    workPlace: "EXPERUM ENTIA",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "Instagram",
        link: "https://www.instagram.com/mulbery_smith_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Facebook",
        link: "https://www.facebook.com/mulberysmithexpertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Twitter",
        link: "https://www.twitter.com/mulberysmithexpertise/",
      },
    ],
    description:
      "Mulbery Smith has developed a solid foundation in corporate travel management and logistics since starting his career in 2015. His clients rely on his resourceful planning skills to deliver effective travel solutions tailored to meet their schedules and preferences.",
    imgSrc: "/assets/images/smiling-calling.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "Carlos Rivera",
        text: "Mulbery made sure everything was taken care of, even the little details. Great work!",
        rating: 3,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Hannah Wilson",
        text: "Reliable and efficient, Mulbery was a pleasure to work with.",
        rating: 4,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Samantha Lee",
        text: "I appreciated Mulbery’s attention to detail and clear communication.",
        rating: 5,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Ethan Taylor",
        text: "Mulbery ensured our trip was smooth and organized. Thanks!",
        rating: 4,
        time: "4 days ago",
      },
    ],
  },
  ,
  {
    id: "4",
    rating: 5,
    slug: "amelia.rivera",
    name: "Amelia Rivera's Expertise",
    preferredLocations: ["Texas", "USA"],
    phoneNumber: "+12348191911",
    location: "Dallas",
    yearStarted: "2012",
    flightsMade: 1895,
    workPlace: "SKYLINE CONSULTING",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "LinkedIn",
        link: "https://www.linkedin.com/in/amelia_rivera_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Twitter",
        link: "https://www.twitter.com/amelia_rivera_expertise/",
      },
    ],
    description:
      "Amelia Rivera, a Texas-based travel specialist, has been delivering customized travel solutions to corporate clients for over a decade. Known for her proactive communication and problem-solving skills, Amelia ensures that every journey is tailored to meet the unique needs of her clients, providing smooth and efficient travel experiences.",
    imgSrc: "/assets/images/smiling-beauty.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "Oliver Jackson",
        text: "Amelia's attention to detail was incredible! She handled everything with grace and efficiency.",
        rating: 5,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Sophia Brown",
        text: "The service was impeccable. Amelia made our trip flawless from start to finish!",
        rating: 5,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "James Clark",
        text: "Very professional and thorough, I highly recommend Amelia for travel planning.",
        rating: 4,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Ella Wright",
        text: "Amelia was fantastic! She coordinated everything, leaving no detail unattended.",
        rating: 5,
        time: "4 days ago",
      },
    ],
  },
  {
    id: "5",
    rating: 4,
    slug: "lucas.chan",
    name: "Lucas Chan's Expertise",
    preferredLocations: ["Washington", "USA"],
    phoneNumber: "+12348191911",
    location: "Seattle",
    yearStarted: "2016",
    flightsMade: 1520,
    workPlace: "HORIZON NAVIGATORS",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "Instagram",
        link: "https://www.instagram.com/lucas_chan_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Facebook",
        link: "https://www.facebook.com/lucaschanexpertise/",
      },
    ],
    description:
      "Lucas Chan, based in Seattle, specializes in personalized travel coordination for business executives. With a strong focus on logistics and customer service, Lucas has built a reputation for ensuring smooth, hassle-free travel for clients across Washington and beyond.",
    imgSrc: "/assets/images/smiling-handsome.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "Emily Harris",
        text: "Lucas was extremely helpful and made sure our travel experience was stress-free!",
        rating: 4,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Jack Thompson",
        text: "Professional and attentive, Lucas was a pleasure to work with.",
        rating: 4,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Liam Martinez",
        text: "Lucas exceeded our expectations, handling all aspects of our travel expertly.",
        rating: 5,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Grace Wilson",
        text: "A reliable and efficient service from start to finish. Lucas is highly recommended!",
        rating: 4,
        time: "4 days ago",
      },
    ],
  },
  {
    id: "6",
    rating: 5,
    slug: "sophia.taylor",
    name: "Sophia Taylor's Expertise",
    preferredLocations: ["New Jersey", "USA"],
    phoneNumber: "+12348191911",
    location: "Newark",
    yearStarted: "2011",
    flightsMade: 2103,
    workPlace: "ELEVATE TRAVEL SOLUTIONS",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "LinkedIn",
        link: "https://www.linkedin.com/in/sophia_taylor_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Twitter",
        link: "https://www.twitter.com/sophia_taylor_expertise/",
      },
    ],
    description:
      "Sophia Taylor is a New Jersey-based travel expert, known for her thorough and client-centered approach. With a focus on business travel, Sophia ensures that her clients' journeys are well-organized and stress-free, creating custom itineraries that accommodate even the most demanding schedules.",
    imgSrc: "/assets/images/smiling-calling.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "Charlotte Evans",
        text: "Sophia’s planning was meticulous and made our trip seamless. Absolutely recommend!",
        rating: 5,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Henry King",
        text: "Sophia went above and beyond, ensuring we had everything we needed for a smooth journey.",
        rating: 5,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Mia Scott",
        text: "Excellent service from Sophia! She made travel easy and worry-free.",
        rating: 4,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Oliver Anderson",
        text: "Sophia’s attention to detail and professionalism were outstanding.",
        rating: 5,
        time: "4 days ago",
      },
    ],
  },
  {
    id: "7",
    rating: 4,
    slug: "ethan.garcia",
    name: "Ethan Garcia's Expertise",
    preferredLocations: ["Illinois", "USA"],
    phoneNumber: "+12348191911",
    location: "Chicago",
    yearStarted: "2014",
    flightsMade: 1679,
    workPlace: "GLOBAL WINGS TRAVEL",
    socials: [
      {
        id: crypto.randomUUID(),
        platform: "Instagram",
        link: "https://www.instagram.com/ethan_garcia_expertise/",
      },
      {
        id: crypto.randomUUID(),
        platform: "Facebook",
        link: "https://www.facebook.com/ethangarciaexpertise/",
      },
    ],
    description:
      "Ethan Garcia is a dedicated travel professional based in Chicago, specializing in managing corporate travel with efficiency and precision. Known for his strong organizational skills and ability to adapt to last-minute changes, Ethan is a preferred travel coordinator for clients who need dependable service.",
    imgSrc: "/assets/images/smiling-beauty.png",
    reviews: [
      {
        id: crypto.randomUUID(),
        name: "Amelia Baker",
        text: "Ethan was quick to respond to our requests and ensured everything was organized perfectly.",
        rating: 4,
        time: "1 day ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Daniel Roberts",
        text: "Ethan’s expertise made our travel experience very smooth and convenient.",
        rating: 5,
        time: "2 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Lily Adams",
        text: "Very reliable and knowledgeable, Ethan took care of everything we needed for our trip.",
        rating: 4,
        time: "3 days ago",
      },
      {
        id: crypto.randomUUID(),
        name: "Mason Hall",
        text: "Excellent service from start to finish. Ethan is highly professional.",
        rating: 4,
        time: "4 days ago",
      },
    ],
  },
];

export const reviews = [
  {
    id: crypto.randomUUID(),
    name: "John Brown",
    text: "Pele provided outstanding support during a complex travel arrangement. His attention to detail and dedication to client satisfaction was unmatched.",
    rating: 5,
    time: "1 day ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Nancy Dean",
    text: "The service was exceptional, from planning to execution. Pele went above and beyond to ensure everything went smoothly.",
    rating: 4,
    time: "2 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Alice Kim",
    text: "Highly recommend Pele's expertise! He made our corporate travel plans seamless and stress-free.",
    rating: 5,
    time: "3 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Mike Johnson",
    text: "A fantastic experience working with Pele. Every detail was meticulously handled!",
    rating: 4,
    time: "4 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Amelia Baker",
    text: "Ethan was quick to respond to our requests and ensured everything was organized perfectly.",
    rating: 4,
    time: "1 day ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Daniel Roberts",
    text: "Ethan’s expertise made our travel experience very smooth and convenient.",
    rating: 5,
    time: "2 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Lily Adams",
    text: "Very reliable and knowledgeable, Ethan took care of everything we needed for our trip.",
    rating: 4,
    time: "3 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Mason Hall",
    text: "Excellent service from start to finish. Ethan is highly professional.",
    rating: 4,
    time: "4 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Charlotte Evans",
    text: "Sophia’s planning was meticulous and made our trip seamless. Absolutely recommend!",
    rating: 5,
    time: "1 day ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Henry King",
    text: "Sophia went above and beyond, ensuring we had everything we needed for a smooth journey.",
    rating: 5,
    time: "2 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Mia Scott",
    text: "Excellent service from Sophia! She made travel easy and worry-free.",
    rating: 4,
    time: "3 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Oliver Anderson",
    text: "Sophia’s attention to detail and professionalism were outstanding.",
    rating: 5,
    time: "4 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Oliver Jackson",
    text: "Amelia's attention to detail was incredible! She handled everything with grace and efficiency.",
    rating: 5,
    time: "1 day ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Sophia Brown",
    text: "The service was impeccable. Amelia made our trip flawless from start to finish!",
    rating: 5,
    time: "2 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "James Clark",
    text: "Very professional and thorough, I highly recommend Amelia for travel planning.",
    rating: 4,
    time: "3 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Ella Wright",
    text: "Amelia was fantastic! She coordinated everything, leaving no detail unattended.",
    rating: 5,
    time: "4 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Carlos Rivera",
    text: "Mulbery made sure everything was taken care of, even the little details. Great work!",
    rating: 3,
    time: "1 day ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Hannah Wilson",
    text: "Reliable and efficient, Mulbery was a pleasure to work with.",
    rating: 4,
    time: "2 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Samantha Lee",
    text: "I appreciated Mulbery's attention to detail and clear communication.",
    rating: 5,
    time: "3 days ago",
  },
  {
    id: crypto.randomUUID(),
    name: "Ethan Taylor",
    text: "Mulbery ensured our trip was smooth and organized. Thanks!",
    rating: 4,
    time: "4 days ago",
  },
];
