import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/dashboard/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
// import { montserrat } from "./fonts";
// import { UserProvider } from "@auth0/nextjs-auth0/client";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import LayoutWrapper from "./LayoutWrapper";
// import Header from "@/components/Header";
// import Footer from "@/components/Footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { id: string };
}>) {
  const session = await auth();
  // if (params.id !== session?.user?.id) {
  //   throw new Error("Invalid user");
  // }
  return <LayoutWrapper>{children}</LayoutWrapper>;
}
